### ISSUE TITLE
only da.gd and ulvis.net working

### ISSUE THREAD

**Issue by muralikodali** [Lemkinator/OneUrl#1]
out of all the services provided in the app only da.gd and ulvis.net are working.
all the remaining services are showing errors.

**Comment by Lemkinator** [comment]
@muralikodali 
All provider seem to be working fine for me. Could you please provide more details about the issue you're experiencing? Specifically, I'd need the input data you're using and the error message you're seeing. If possible, including a log would be most helpful. Thanks!
